<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\ServiceCategory;
use Illuminate\Database\Seeder;

class ServiceSeeder extends Seeder
{
    public function run(): void
    {
        $categoryIds = ServiceCategory::pluck('id', 'slug')->toArray();

        $category = fn (string $slug) => $categoryIds[$slug] ?? null;

        $services = [
            [
                'service_category_id' => $category('parcours-linguistique'),
                'slug' => 'francais-express',
                'name_fr' => 'Français Express',
                'name_en' => 'Français Express',
                'short_description_fr' => 'Progressez vite, gagnez en confiance',
                'short_description_en' => 'Progress fast, gain confidence',
                'description_fr' => "Vous souhaitez améliorer votre français rapidement pour le travail, les études ou votre vie quotidienne ? Français Express est un programme intensif conçu pour vous faire avancer en seulement 4 semaines. Grâce à un encadrement expert et à un rythme soutenu mais accessible, vous verrez vos compétences évoluer dès les premiers jours.",
                'description_en' => "Do you want to improve your French quickly for work, studies or daily life? Français Express is an intensive program designed to help you progress in just 4 weeks.",
                'duration' => '4 semaines',
                'price' => '600 $',
                'image' => 'img/banner-english-express.png',
                'order' => 1,
            ],
            [
                'service_category_id' => $category('parcours-linguistique'),
                'slug' => 'soiree-linguo',
                'name_fr' => 'Soirée Linguo',
                'name_en' => 'Soirée Linguo',
                'short_description_fr' => 'Apprenez le français sans bouleverser votre horaire',
                'short_description_en' => 'Learn French without disrupting your schedule',
                'description_fr' => "Un cours en soirée pour les adultes qui souhaitent apprendre le français à leur rythme, sans compromettre leurs engagements professionnels ou familiaux.",
                'duration' => '8 semaines',
                'price' => '600 $',
                'image' => 'img/banner-soiree-linguo.png',
                'order' => 2,
            ],
            [
                'service_category_id' => $category('parcours-linguistique'),
                'slug' => 'samedis-en-francais',
                'name_fr' => 'Samedis en français',
                'name_en' => 'Saturdays in French',
                'short_description_fr' => 'Apprenez le français chaque samedi',
                'short_description_en' => 'Learn French every Saturday',
                'description_fr' => "Un cours hebdomadaire le samedi pour les adultes qui souhaitent apprendre le français tout en conciliant leurs autres engagements.",
                'duration' => '12 semaines',
                'price' => '600 $',
                'image' => 'img/banner-samedi-francais.png',
                'order' => 3,
            ],
            [
                'service_category_id' => $category('english-linguistic-pathway'),
                'slug' => 'english-express',
                'name_fr' => 'English Express',
                'name_en' => 'English Express',
                'short_description_fr' => 'English Express - Intensive English Course',
                'short_description_en' => 'Intensive English course in small groups',
                'description_fr' => "Un programme d'anglais intensif conçu pour les adultes qui souhaitent progresser rapidement.",
                'duration' => '4 weeks',
                'price' => '600 $',
                'image' => 'img/banner-english-express-2.png',
                'order' => 4,
            ],
            [
                'service_category_id' => $category('english-linguistic-pathway'),
                'slug' => 'evening-lingo',
                'name_fr' => 'Evening Lingo',
                'name_en' => 'Evening Lingo',
                'short_description_fr' => 'English course in the evening',
                'short_description_en' => 'Learn English without disrupting your schedule',
                'description_fr' => "Un cours d'anglais en soirée pour les adultes qui souhaitent apprendre à leur rythme.",
                'duration' => '8 weeks',
                'price' => '600 $',
                'image' => 'img/banner-evening-lingo.png',
                'order' => 5,
            ],
            [
                'service_category_id' => $category('english-linguistic-pathway'),
                'slug' => 'saturdays-in-english',
                'name_fr' => 'Saturdays in English',
                'name_en' => 'Saturdays in English',
                'short_description_fr' => 'English course every Saturday',
                'short_description_en' => 'Learn English every Saturday',
                'description_fr' => "Un cours d'anglais hebdomadaire le samedi pour les adultes.",
                'duration' => '12 weeks',
                'price' => '600 $',
                'image' => 'img/banner-samedi-anglais.png',
                'order' => 6,
            ],
            [
                'service_category_id' => $category('cap-sur-l-oral'),
                'slug' => 'oral-b-partiel',
                'name_fr' => 'Oral B - Partiel',
                'name_en' => 'Oral B - Part-time',
                'short_description_fr' => 'Niveau intermédiaire - Cours en soirée',
                'short_description_en' => 'Intermediate level - Evening course',
                'description_fr' => "Cap sur l'oral B est conçu pour les adultes de niveau intermédiaire qui souhaitent améliorer leur expression orale en français.",
                'duration' => '8 semaines',
                'price' => '600 $',
                'image' => 'img/banner-oral-b-partiel.png',
                'order' => 7,
            ],
            [
                'service_category_id' => $category('cap-sur-l-oral'),
                'slug' => 'oral-b-intensif',
                'name_fr' => 'Oral B - Intensif',
                'name_en' => 'Oral B - Intensive',
                'short_description_fr' => 'Niveau intermédiaire - Cours intensif',
                'short_description_en' => 'Intermediate level - Intensive course',
                'description_fr' => "Cap sur l'oral B Intensif est conçu pour les adultes de niveau intermédiaire qui souhaitent progresser rapidement.",
                'duration' => '4 semaines',
                'price' => '600 $',
                'image' => 'img/banner-oral-b-intensif.png',
                'order' => 8,
            ],
            [
                'service_category_id' => $category('cap-sur-l-oral'),
                'slug' => 'oral-c-partiel',
                'name_fr' => 'Oral C - Partiel',
                'name_en' => 'Oral C - Part-time',
                'short_description_fr' => 'Niveau avancé - Cours en soirée',
                'short_description_en' => 'Advanced level - Evening course',
                'description_fr' => "Cap sur l'oral C est conçu pour les adultes de niveau avancé qui souhaitent perfectionner leur expression orale.",
                'duration' => '8 semaines',
                'price' => '600 $',
                'image' => 'img/banner-oral-c-partiel.png',
                'order' => 9,
            ],
            [
                'service_category_id' => $category('cap-sur-l-oral'),
                'slug' => 'oral-c-intensif',
                'name_fr' => 'Oral C - Intensif',
                'name_en' => 'Oral C - Intensive',
                'short_description_fr' => 'Niveau avancé - Cours intensif',
                'short_description_en' => 'Advanced level - Intensive course',
                'description_fr' => "Cap sur l'oral C Intensif est conçu pour les adultes de niveau avancé qui souhaitent progresser rapidement.",
                'duration' => '4 semaines',
                'price' => '600 $',
                'image' => 'img/banner-oral-c-intensif.png',
                'order' => 10,
            ],
            [
                'service_category_id' => $category('tcf-quebec'),
                'slug' => 'tcf-quebec-partiel',
                'name_fr' => 'TCF Québec - Partiel',
                'name_en' => 'TCF Québec - Part-time',
                'short_description_fr' => 'Préparation au TCF Québec en soirée',
                'short_description_en' => 'TCF Québec preparation - Evening',
                'description_fr' => "Préparez efficacement le TCF Québec, le test officiel exigé par le gouvernement du Québec pour l'immigration.",
                'duration' => '8 semaines',
                'price' => '600 $',
                'image' => 'img/banner-tcf-quebec-partiel.png',
                'order' => 11,
            ],
            [
                'service_category_id' => $category('tcf-quebec'),
                'slug' => 'tcf-quebec-intensif',
                'name_fr' => 'TCF Québec - Intensif',
                'name_en' => 'TCF Québec - Intensive',
                'short_description_fr' => 'Préparation intensive au TCF Québec',
                'short_description_en' => 'Intensive TCF Québec preparation',
                'description_fr' => "Préparez le TCF Québec de manière intensive avec un programme accéléré.",
                'duration' => '4 semaines',
                'price' => '600 $',
                'image' => 'img/banner-tcf-quebec-intensif.png',
                'order' => 12,
            ],
            [
                'service_category_id' => $category('tcf-canada'),
                'slug' => 'tcf-canada-partiel',
                'name_fr' => 'TCF Canada - Partiel',
                'name_en' => 'TCF Canada - Part-time',
                'short_description_fr' => 'Préparation au TCF Canada en soirée',
                'short_description_en' => 'TCF Canada preparation - Evening',
                'description_fr' => "Préparez efficacement le TCF Canada, le test officiel requis pour l'immigration auprès d'IRCC.",
                'duration' => '8 semaines',
                'price' => '600 $',
                'image' => 'img/banner-tcf-canada-partiel.png',
                'order' => 13,
            ],
            [
                'service_category_id' => $category('tcf-canada'),
                'slug' => 'tcf-canada-intensif',
                'name_fr' => 'TCF Canada - Intensif',
                'name_en' => 'TCF Canada - Intensive',
                'short_description_fr' => 'Préparation intensive au TCF Canada',
                'short_description_en' => 'Intensive TCF Canada preparation',
                'description_fr' => "Préparez le TCF Canada de manière intensive avec un programme accéléré.",
                'duration' => '4 semaines',
                'price' => '600 $',
                'image' => 'img/banner-tcf-canada-intensif.png',
                'order' => 14,
            ],
            [
                'service_category_id' => $category('formation-en-solo'),
                'slug' => 'solo-5h',
                'name_fr' => 'Solo 5h',
                'name_en' => 'Solo 5h',
                'short_description_fr' => 'Pack de 5 heures de formation individuelle',
                'short_description_en' => '5-hour private training package',
                'description_fr' => "Un accompagnement individuel flexible de 5 heures pour atteindre vos objectifs linguistiques.",
                'duration' => '5 heures',
                'price' => '300 $',
                'image' => 'img/solo-5h.png',
                'order' => 15,
            ],
            [
                'service_category_id' => $category('formation-en-solo'),
                'slug' => 'solo-10h',
                'name_fr' => 'Solo 10h',
                'name_en' => 'Solo 10h',
                'short_description_fr' => 'Pack de 10 heures de formation individuelle',
                'short_description_en' => '10-hour private training package',
                'description_fr' => "Un accompagnement individuel flexible de 10 heures pour approfondir votre apprentissage.",
                'duration' => '10 heures',
                'price' => '550 $',
                'image' => 'img/solo-10h.png',
                'order' => 16,
            ],
            [
                'service_category_id' => $category('formation-en-solo'),
                'slug' => 'solo-15h',
                'name_fr' => 'Solo 15h',
                'name_en' => 'Solo 15h',
                'short_description_fr' => 'Pack de 15 heures de formation individuelle',
                'short_description_en' => '15-hour private training package',
                'description_fr' => "Un accompagnement individuel flexible de 15 heures pour une progression significative.",
                'duration' => '15 heures',
                'price' => '750 $',
                'image' => 'img/solo-15h.png',
                'order' => 17,
            ],
            [
                'service_category_id' => $category('formation-en-solo'),
                'slug' => 'solo-20h',
                'name_fr' => 'Solo 20h',
                'name_en' => 'Solo 20h',
                'short_description_fr' => 'Pack de 20 heures de formation individuelle',
                'short_description_en' => '20-hour private training package',
                'description_fr' => "Un accompagnement individuel flexible de 20 heures pour une maîtrise approfondie.",
                'duration' => '20 heures',
                'price' => '900 $',
                'image' => 'img/solo-20h.png',
                'order' => 18,
            ],
            [
                'service_category_id' => $category('ateliers'),
                'slug' => 'atelier-conversation',
                'name_fr' => 'Atelier Conversation',
                'name_en' => 'Conversation Workshop',
                'short_description_fr' => 'Pratiquez la conversation en français',
                'short_description_en' => 'Practice conversation in French',
                'description_fr' => "Un atelier interactif pour pratiquer la conversation en français dans une ambiance conviviale.",
                'duration' => '2 heures/session',
                'price' => '20 $/session',
                'image' => 'img/atelier-conversation.png',
                'order' => 19,
            ],
            [
                'service_category_id' => $category('ateliers'),
                'slug' => 'atelier-culture-canada',
                'name_fr' => 'Atelier Culture du Canada',
                'name_en' => 'Canadian Culture Workshop',
                'short_description_fr' => 'Découvrez la culture canadienne en français',
                'short_description_en' => 'Discover Canadian culture in French',
                'description_fr' => "Un atelier thématique pour découvrir la culture canadienne tout en pratiquant le français.",
                'duration' => '2 heures/session',
                'price' => '20 $/session',
                'image' => 'img/atelier-culture-canada.png',
                'order' => 20,
            ],
            [
                'service_category_id' => $category('ateliers'),
                'slug' => 'atelier-maintien',
                'name_fr' => 'Atelier Maintien',
                'name_en' => 'Maintenance Workshop',
                'short_description_fr' => 'Maintenez et perfectionnez votre français',
                'short_description_en' => 'Maintain and improve your French',
                'description_fr' => "Un atelier pour maintenir et perfectionner votre français oral dans une ambiance détendue.",
                'duration' => '2 heures/session',
                'price' => '20 $/session',
                'image' => 'img/atelier-maintien.png',
                'order' => 21,
            ],
        ];

        foreach ($services as $data) {
            Service::create($data);
        }
    }
}
