<?php

namespace Database\Seeders;

use App\Models\ServiceCategory;
use Illuminate\Database\Seeder;

class ServiceCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            [
                'slug' => 'parcours-linguistique',
                'name_fr' => 'Parcours linguistique',
                'name_en' => 'Linguistic Pathway',
                'description_fr' => 'Cours de groupe en petit groupe pour progresser avec confiance',
                'description_en' => 'Group courses in small groups to progress with confidence',
                'image' => 'img/home/parcours-linguistiques-new.png',
                'banner_image' => 'img/hero-parcours-linguistiques.png',
                'order' => 1,
                'hero_subtitle' => 'Un programme complet décliné en 3 parcours francophones adaptés à vos objectifs, votre emploi du temps et votre rythme d\'apprentissage.',
                'hero_chips' => [
                    ['text' => '3 parcours', 'icon' => '<i class="fas fa-layer-group"></i>'],
                    ['text' => 'Petits groupes', 'icon' => '<i class="fas fa-users"></i>', 'class' => 'm4-chip-green'],
                    ['text' => 'Flexible', 'icon' => '<i class="fas fa-calendar-check"></i>', 'class' => 'm4-chip-indigo'],
                    ['text' => 'Français', 'icon' => '<i class="fas fa-language"></i>', 'class' => 'm4-chip-amber'],
                ],
                'programs_intro' => 'Trois programmes conçus pour s\'adapter à votre rythme, votre emploi du temps et vos objectifs. Sélectionnez la formule qui vous correspond.',
                'description_html' => '<p>Rejoignez un programme conçu pour vous faire progresser réellement, dans un environnement motivant et stimulant, spécialement pensé pour les adultes.</p><p>Nos cours de groupe à effectif réduit (maximum 5 participants) vous offrent bien plus qu\'une simple formation : vous bénéficiez d\'un espace dynamique où vous pouvez pratiquer, poser vos questions et développer votre confiance à chaque séance.</p><p>Grâce à une approche structurée et centrée sur vos objectifs, vous progressez plus rapidement et plus efficacement, tout en étant accompagné à chaque étape de votre apprentissage.</p><p>Que vous souhaitiez améliorer vos compétences pour le travail, vos études ou votre vie quotidienne, ce programme vous donne les outils et l\'encadrement nécessaires pour atteindre vos objectifs.</p>',
                'benefits_title' => 'Pourquoi choisir un parcours <span class="text-gradient">linguistique</span> ?',
                'benefits_intro' => 'Un apprentissage en groupe structuré et stimulant, pensé pour des adultes qui veulent progresser efficacement et durablement.',
                'benefits' => [
                    ['icon' => '👥', 'title' => 'Petits groupes dynamiques', 'text' => 'Maximum 5 participants par groupe pour un encadrement personnalisé et des échanges riches entre apprenants.'],
                    ['icon' => '🎯', 'title' => 'Trois programmes adaptés', 'text' => 'Choisissez le parcours qui correspond à votre rythme : intensif, en soirée ou le samedi, selon vos disponibilités.'],
                    ['icon' => '📈', 'title' => 'Progression structurée', 'text' => 'Un programme progressif et cohérent qui vous permet de monter en compétences étape par étape, avec un suivi régulier.'],
                    ['icon' => '🤝', 'title' => 'Apprentissage collaboratif', 'text' => 'Pratiquez la conversation dans un cadre bienveillant, échangez avec d\'autres apprenants et gagnez en confiance à l\'oral.'],
                ],
                'audience_intro' => 'Le parcours linguistique s\'adresse à tous les adultes souhaitant progresser en français dans un cadre stimulant et encadré.',
                'audience' => [
                    ['icon' => '💼', 'title' => 'Professionnels en activité', 'text' => 'Vous souhaitez améliorer votre français pour le travail ? Les cours en soirée et le samedi s\'adaptent à votre emploi du temps.'],
                    ['icon' => '🌍', 'title' => 'Nouveaux arrivants au Québec', 'text' => 'Intégrez la vie québécoise plus facilement grâce à un français opérationnel, appris dans un contexte communicatif réel.'],
                    ['icon' => '📚', 'title' => 'Apprenants en reconversion', 'text' => 'Renforcez vos compétences linguistiques pour accéder à de nouvelles opportunités professionnelles ou académiques.'],
                    ['icon' => '🌱', 'title' => 'Toute personne motivée', 'text' => 'Que vous soyez débutant ou intermédiaire, le parcours linguistique vous offre un cadre structuré pour progresser à votre rythme.'],
                ],
            ],
            [
                'slug' => 'english-linguistic-pathway',
                'name_fr' => 'English Linguistic Pathway',
                'name_en' => 'English Linguistic Pathway',
                'description_fr' => 'English courses designed to help you make real progress in a motivating environment',
                'description_en' => 'English courses designed to help you make real progress in a motivating environment',
                'image' => 'img/home/english-linguistic-pathway-new.png',
                'banner_image' => 'img/hero-english.png',
                'order' => 2,
                'hero_subtitle' => 'Join a program designed to help you make real progress in a motivating and stimulating environment, specially created for adult learners. Choose the pathway that fits your goals, your schedule, and your rhythm.',
                'hero_chips' => [
                    ['text' => '3 pathways', 'icon' => '<i class="fas fa-layer-group"></i>'],
                    ['text' => 'Small groups', 'icon' => '<i class="fas fa-users"></i>', 'class' => 'm4-chip-green'],
                    ['text' => 'Flexible', 'icon' => '<i class="fas fa-calendar-check"></i>', 'class' => 'm4-chip-indigo'],
                    ['text' => 'English', 'icon' => '<i class="fas fa-language"></i>', 'class' => 'm4-chip-amber'],
                ],
                'programs_intro' => 'Three programs designed to fit your schedule, your goals, and your learning rhythm. Select the format that works for you.',
                'description_html' => '<p>Join a program designed to help you make real progress in a motivating and stimulating environment, specially created for adult learners.</p><p>Our small-group classes (maximum of 5 participants) offer far more than a simple course: you benefit from a dynamic space where you can practice, ask questions, and build confidence in every session.</p><ul><li><i class="fas fa-check-circle"></i> Intensive 60-hour Express pathway (4 weeks, Mon–Fri)</li><li><i class="fas fa-check-circle"></i> Flexible 30-hour Evening Lingo pathway (10 weeks, 1x/week)</li><li><i class="fas fa-check-circle"></i> Immersive 30-hour Saturdays in English pathway (5 Saturdays)</li><li><i class="fas fa-check-circle"></i> Small groups of 5 participants maximum</li><li><i class="fas fa-check-circle"></i> Expert guidance from certified instructors</li><li><i class="fas fa-check-circle"></i> Free initial assessment and personalized advice</li><li><i class="fas fa-check-circle"></i> Flexible scheduling to match your availability</li></ul><p>With a structured approach centered on your goals, you progress faster and more effectively, while receiving guidance at every step of your learning journey.</p><p>Whether you want to improve your skills for work, studies, or everyday life, this program gives you the tools and support you need to reach your goals.</p>',
                'benefits_title' => 'Why choose the English <span class="text-gradient">Linguistic Pathway</span>?',
                'benefits_intro' => 'A structured program designed for adults who want real results, expert guidance, and a supportive learning environment.',
                'benefits' => [
                    ['icon' => '👥', 'title' => 'Small group sizes', 'text' => 'With a maximum of 5 participants, you get personalized attention, more speaking time, and a supportive learning environment.'],
                    ['icon' => '🎯', 'title' => 'Goal-oriented approach', 'text' => 'Each pathway is built around clear objectives so you progress faster and more effectively, with guidance at every step.'],
                    ['icon' => '🗓️', 'title' => 'Flexible scheduling', 'text' => 'Choose from intensive daytime, evening, or Saturday formats — designed to fit your work–life balance and availability.'],
                    ['icon' => '🏆', 'title' => 'Real, measurable progress', 'text' => 'A dynamic space where you practice, build confidence, and see tangible improvement from the very first week.'],
                ],
                'audience_intro' => 'The English Linguistic Pathway is designed for adult learners who want to improve their English in a structured, motivating environment.',
                'audience' => [
                    ['icon' => '💼', 'title' => 'Working professionals', 'text' => 'You need English for your career but have a busy schedule? Our evening and Saturday pathways fit perfectly into your work–life routine.'],
                    ['icon' => '📚', 'title' => 'Students and lifelong learners', 'text' => 'Whether you\'re preparing for studies, exams, or personal growth, our structured program gives you the tools and confidence to succeed.'],
                    ['icon' => '🌍', 'title' => 'Newcomers to Canada', 'text' => 'Looking to integrate into English-speaking environments? Our pathway helps you build the fluency and confidence you need for daily life and work.'],
                ],
            ],
            [
                'slug' => 'cap-sur-l-oral',
                'name_fr' => 'Cap sur l\'oral',
                'name_en' => 'Oral Focus',
                'description_fr' => 'Maîtrisez l\'expression orale avec des parcours collaboratifs en petit groupe',
                'description_en' => 'Master oral expression with collaborative pathways in small groups',
                'image' => 'img/home/cap-sur-l-oral-new.png',
                'banner_image' => 'img/home/banner-linguotest.png',
                'order' => 3,
                'hero_subtitle' => 'Deux parcours collaboratifs en petit groupe pour maîtriser l\'oral avec confiance et précision.',
                'hero_chips' => [
                    ['text' => 'Niveaux B & C', 'icon' => '<i class="fas fa-bullseye"></i>'],
                    ['text' => 'Oral professionnel', 'icon' => '<i class="fas fa-comments"></i>', 'class' => 'm4-chip-green'],
                    ['text' => 'Petits groupes', 'icon' => '<i class="fas fa-users"></i>', 'class' => 'm4-chip-indigo'],
                    ['text' => '4–10 semaines', 'icon' => '<i class="fas fa-clock"></i>', 'class' => 'm4-chip-amber'],
                ],
                'programs_intro' => 'Quatre programmes conçus pour vous préparer au TCO, adaptés à votre niveau et à votre rythme.',
                'description_html' => '<p>Cap sur l\'oral réunit des parcours collaboratifs en petit groupe (maximum 5 participants) pour maîtriser l\'expression orale en français avec confiance et précision, du niveau B au niveau C.</p><p>Chaque parcours est proposé en format temps partiel ou intensif et prépare au test de compétence orale (TCO) du gouvernement du Canada, avec des exercices et des simulations réalistes.</p><p>Un environnement bienveillant et exigeant pour oser parler, corriger vos réflexes et gagner en assurance à l\'oral.</p>',
                'benefits_title' => 'Pourquoi choisir <span class="text-gradient">Cap sur l\'oral</span> ?',
                'benefits_intro' => 'Un parcours collaboratif en petit groupe pour maîtriser l\'oral avec confiance et précision.',
                'benefits' => [
                    ['icon' => '👥', 'title' => 'Petits groupes (max 5)', 'text' => 'Un cadre intime et stimulant où chacun bénéficie d\'un temps de parole suffisant et d\'attention individualisée.'],
                    ['icon' => '🎯', 'title' => 'Parcours structurés', 'text' => 'Des programmes progressifs, du niveau B au C, conçus pour vous guider étape par étape vers la maîtrise de l\'oral.'],
                    ['icon' => '🗣️', 'title' => 'Préparation au TCO', 'text' => 'Un entraînement ciblé au test de compétence orale du gouvernement du Canada, avec des exercices et simulations réalistes.'],
                    ['icon' => '🏆', 'title' => 'Confiance et précision', 'text' => 'Un environnement bienveillant et exigeant pour oser parler, corriger vos réflexes et gagner en assurance à l\'oral.'],
                ],
                'audience_intro' => 'Cap sur l\'oral s\'adresse à tous les adultes souhaitant développer ou perfectionner leur expression orale en français.',
                'audience' => [
                    ['icon' => '💼', 'title' => 'Professionnels francophones', 'text' => 'Vous travaillez en français mais souhaitez gagner en fluidité, en précision ou en aisance pour vos réunions et présentations professionnelles.'],
                    ['icon' => '📝', 'title' => 'Candidats au TCO', 'text' => 'Vous préparez le test de compétence orale du gouvernement du Canada et avez besoin d\'un entraînement ciblé pour atteindre le niveau B ou C.'],
                    ['icon' => '🔝', 'title' => 'Apprenants intermédiaires à avancés', 'text' => 'Vous avez déjà des bases solides en français et vous voulez passer le cap vers une expression orale plus naturelle, nuancée et stratégique.'],
                ],
            ],
            [
                'slug' => 'tcf-quebec',
                'name_fr' => 'TCF Québec',
                'name_en' => 'TCF Québec',
                'description_fr' => 'Préparation au TCF Québec pour l\'immigration',
                'description_en' => 'TCF Québec preparation for immigration',
                'image' => 'img/home/tcf-quebec-new.png',
                'order' => 4,
                'hero_subtitle' => 'Le TCF Québec est un test officiel exigé par le gouvernement du Québec dans le cadre d\'une demande d\'immigration ou du Programme de l\'expérience québécoise (PEQ). Le test évalue votre capacité à comprendre et communiquer en français, à l\'oral comme à l\'écrit.',
                'hero_chips' => [
                    ['text' => 'Immigration Québec', 'icon' => '<i class="fas fa-passport"></i>'],
                    ['text' => 'Officiel', 'icon' => '<i class="fas fa-certificate"></i>', 'class' => 'm4-chip-green'],
                    ['text' => 'Petits groupes', 'icon' => '<i class="fas fa-users"></i>', 'class' => 'm4-chip-indigo'],
                    ['text' => '7–14 semaines', 'icon' => '<i class="fas fa-clock"></i>', 'class' => 'm4-chip-amber'],
                ],
                'programs_intro' => 'Deux formats pour le TCF Québec, adaptés à votre rythme et à vos objectifs.',
                'description_html' => '<p>Le TCF Québec est un test officiel exigé par le gouvernement du Québec dans le cadre d\'une demande d\'immigration ou du Programme de l\'expérience québécoise (PEQ).</p><p>Même si cela peut sembler impressionnant au premier regard, il est en réalité beaucoup plus accessible qu\'on ne l\'imagine.</p><p>Le test sert simplement à démontrer votre capacité à comprendre et communiquer en français dans des situations de la vie quotidienne, à l\'oral comme à l\'écrit.</p><p>Il permet de :</p><ul><li><i class="fas fa-check-circle"></i> Prouver officiellement votre niveau de français pour l\'immigration</li><li><i class="fas fa-check-circle"></i> Obtenir des points dans le système de sélection du Québec</li><li><i class="fas fa-check-circle"></i> Attester vos compétences en compréhension orale, compréhension écrite, expression orale et expression écrite</li><li><i class="fas fa-check-circle"></i> Fournir une preuve reconnue par le MIFI, valide 2 ans</li></ul><p>Les épreuves orales sont particulièrement importantes, car elles peuvent rapporter jusqu\'à 14 points sur 16. Mais rassurez-vous : avec une préparation adaptée, tout devient beaucoup plus clair et maîtrisable.</p><p>Chez Cultulangues, nous vous guidons étape par étape pour que vous sachiez exactement comment répondre, comment structurer vos idées et comment gérer votre temps le jour du test.</p>',
                'benefits_title' => 'Pourquoi préparer votre TCF Québec <span class="text-gradient">avec nous</span> ?',
                'benefits_intro' => 'Une préparation structurée et rassurante pour obtenir le niveau requis pour votre immigration au Québec.',
                'benefits' => [
                    ['icon' => '🎯', 'title' => 'Préparation ciblée', 'text' => 'Stratégies efficaces pour chaque épreuve : compréhension orale, écrite, expression orale et écrite.'],
                    ['icon' => '👥', 'title' => 'Petits groupes', 'text' => 'Maximum 5 participants pour un accompagnement personnalisé et des interactions de qualité.'],
                    ['icon' => '📋', 'title' => 'Simulations d\'examen', 'text' => 'Entraînez-vous dans des conditions réelles avec des tests blancs et des corrections détaillées.'],
                    ['icon' => '🤝', 'title' => 'Accompagnement bienveillant', 'text' => 'Un espace sans jugement où vous gagnez en confiance et en sérénité le jour du test.'],
                ],
                'audience_intro' => 'Le TCF Québec est destiné aux personnes souhaitant immigrer au Québec ou obtenir le PEQ.',
                'audience' => [
                    ['icon' => '🇨🇦', 'title' => 'Candidats à l\'immigration québécoise', 'text' => 'Obtenez le score nécessaire pour votre demande d\'immigration au Québec auprès du MIFI.'],
                    ['icon' => '📝', 'title' => 'Candidats au PEQ', 'text' => 'Le Programme de l\'expérience québécoise exige une preuve de niveau de français. Le TCF Québec est reconnu.'],
                    ['icon' => '💼', 'title' => 'Adultes souhaitant s\'installer au Québec', 'text' => 'Une préparation complète et rassurante pour démarrer votre nouvelle vie au Québec en toute confiance.'],
                ],
            ],
            [
                'slug' => 'tcf-canada',
                'name_fr' => 'TCF Canada',
                'name_en' => 'TCF Canada',
                'description_fr' => 'Préparation au TCF Canada pour l\'immigration IRCC',
                'description_en' => 'TCF Canada preparation for IRCC immigration',
                'image' => 'img/home/tcf-canada-new.png',
                'order' => 5,
                'hero_subtitle' => 'Le TCF Canada est un test officiel requis pour les démarches d\'immigration auprès d\'IRCC. Le test évalue votre capacité à comprendre et communiquer en français dans des situations du quotidien, à l\'oral comme à l\'écrit.',
                'hero_chips' => [
                    ['text' => 'Immigration IRCC', 'icon' => '<i class="fas fa-passport"></i>'],
                    ['text' => 'Officiel', 'icon' => '<i class="fas fa-certificate"></i>', 'class' => 'm4-chip-green'],
                    ['text' => 'Petits groupes', 'icon' => '<i class="fas fa-users"></i>', 'class' => 'm4-chip-indigo'],
                    ['text' => '7–14 semaines', 'icon' => '<i class="fas fa-clock"></i>', 'class' => 'm4-chip-amber'],
                ],
                'programs_intro' => 'Deux formats pour le TCF Canada, adaptés à votre rythme et à vos objectifs.',
                'description_html' => '<p>Le TCF Canada est un test officiel requis pour les démarches d\'immigration auprès d\'IRCC, mais rassurez-vous : avec une préparation adaptée, il devient beaucoup plus accessible.</p><p>Le test évalue votre capacité à comprendre et communiquer en français dans des situations du quotidien, à l\'oral comme à l\'écrit.</p><p>Chez Cultulangues, nous vous guidons pas à pas pour que vous sachiez exactement quoi faire, comment répondre et comment gérer votre temps le jour de l\'examen.</p><p>Le TCF Canada évalue quatre compétences essentielles :</p><ul><li><i class="fas fa-check-circle"></i> Compréhension écrite : lire et comprendre différents types de textes</li><li><i class="fas fa-check-circle"></i> Compréhension orale : comprendre dialogues, médias et discours</li><li><i class="fas fa-check-circle"></i> Expression écrite : rédiger des textes clairs et structurés</li><li><i class="fas fa-check-circle"></i> Expression orale : communiquer, argumenter et défendre un point de vue</li></ul><p>Notre objectif est simple : vous aider à gagner en confiance, à progresser sereinement et à obtenir le meilleur score possible pour votre projet d\'immigration.</p>',
                'benefits_title' => 'Pourquoi préparer votre TCF Canada <span class="text-gradient">avec nous</span> ?',
                'benefits_intro' => 'Une préparation structurée et claire pour obtenir le meilleur score possible pour votre immigration IRCC.',
                'benefits' => [
                    ['icon' => '🎯', 'title' => 'Préparation ciblée IRCC', 'text' => 'Stratégies spécifiques pour maximiser vos points dans chaque compétence évaluée par IRCC.'],
                    ['icon' => '👥', 'title' => 'Petits groupes', 'text' => 'Maximum 5 participants pour un accompagnement personnalisé et des interactions de qualité.'],
                    ['icon' => '📋', 'title' => '4 compétences évaluées', 'text' => 'Compréhension écrite, compréhension orale, expression écrite et expression orale — nous couvrons tout.'],
                    ['icon' => '🤝', 'title' => 'Environnement sans pression', 'text' => 'Un cadre bienveillant et clair pour progresser sereinement et gagner en confiance.'],
                ],
                'audience_intro' => 'Le TCF Canada est requis pour les démarches d\'immigration auprès d\'IRCC.',
                'audience' => [
                    ['icon' => '🇨🇦', 'title' => 'Candidats à l\'immigration IRCC', 'text' => 'Obtenez la preuve de niveau de français requise pour votre demande d\'immigration au Canada fédéral.'],
                    ['icon' => '📝', 'title' => 'Candidats au CLB', 'text' => 'Atteignez le niveau CLB requis pour votre programme d\'immigration avec un score compétitif.'],
                    ['icon' => '💼', 'title' => 'Adultes en projet d\'immigration', 'text' => 'Une préparation claire et rassurante pour démarrer votre vie au Canada en toute confiance.'],
                ],
            ],
            [
                'slug' => 'formation-en-solo',
                'name_fr' => 'Formation en solo',
                'name_en' => 'Private Lessons',
                'description_fr' => 'Accompagnement 1-to-1 flexible et 100% personnalisé',
                'description_en' => 'Flexible 1-to-1 support, 100% personalized',
                'image' => 'img/home/formation-solo-new.png',
                'banner_image' => 'img/hero-cours-solo-new.png',
                'order' => 6,
                'hero_subtitle' => 'La formule la plus flexible et la plus efficace pour atteindre rapidement vos objectifs linguistiques. Choisissez exactement ce dont vous avez besoin.',
                'hero_chips' => [
                    ['text' => 'Cours 1-to-1', 'icon' => '<i class="fas fa-user"></i>'],
                    ['text' => '5–20 heures', 'icon' => '<i class="fas fa-clock"></i>', 'class' => 'm4-chip-green'],
                    ['text' => 'Flexible', 'icon' => '<i class="fas fa-calendar-check"></i>', 'class' => 'm4-chip-indigo'],
                    ['text' => '38–45 $/h', 'icon' => '<i class="fas fa-tag"></i>', 'class' => 'm4-chip-amber'],
                ],
                'programs_intro' => 'Choisissez le nombre d\'heures qui vous convient. Tarifs dégressifs selon le forfait.',
                'description_html' => '<p>Boostez votre français avec les cours solo Cultulangues, la formule la plus flexible et la plus efficace pour atteindre rapidement vos objectifs linguistiques.</p><p>Choisissez exactement ce dont vous avez besoin grâce à nos cours à la carte :</p><ul><li><i class="fas fa-check-circle"></i> Un parcours linguistique complet</li><li><i class="fas fa-check-circle"></i> Un programme Cap sur l\'oral</li><li><i class="fas fa-check-circle"></i> Une préparation ciblée au TCF</li><li><i class="fas fa-check-circle"></i> Un module pour rafraîchir votre français</li><li><i class="fas fa-check-circle"></i> Un entraînement intensif aux tests écrits de la fonction publique</li><li><i class="fas fa-check-circle"></i> Des simulations d\'examen</li><li><i class="fas fa-check-circle"></i> Des séances pour maintenir votre niveau en toute simplicité</li></ul><p>Avec nos forfaits de 5 h, 10 h, 15 h ou 20 h, vous avancez à votre rythme, avec un accompagnement sur mesure et des résultats concrets.</p>',
                'benefits_title' => 'Pourquoi choisir la formule <span class="text-gradient">solo</span> ?',
                'benefits_intro' => 'Un accompagnement individuel pensé pour adultes exigeants qui veulent des résultats rapides et durables.',
                'benefits' => [
                    ['icon' => '📅', 'title' => 'Flexibilité totale', 'text' => 'Vous choisissez vos jours et horaires selon votre emploi du temps. Aucune contrainte de calendrier.'],
                    ['icon' => '🎯', 'title' => 'Personnalisation complète', 'text' => 'Un programme sur mesure adapté à votre niveau, vos objectifs et votre rythme d\'apprentissage.'],
                    ['icon' => '📦', 'title' => 'Forfaits 5h à 20h', 'text' => 'Choisissez le forfait qui vous correspond : 5h, 10h, 15h ou 20h. Tarif dégressif selon le volume.'],
                    ['icon' => '🏆', 'title' => 'Résultats concrets', 'text' => 'Un accompagnement individuel garantissant une progression rapide et mesurable dès les premières séances.'],
                ],
                'audience_intro' => 'La formation en solo s\'adresse à tous les adultes souhaitant progresser efficacement en français ou en anglais.',
                'audience' => [
                    ['icon' => '💼', 'title' => 'Professionnels en activité', 'text' => 'Vous manquez de temps ? Nos cours solo s\'adaptent à votre emploi du temps chargé avec des séances flexibles en journée, en soirée ou le week-end.'],
                    ['icon' => '📝', 'title' => 'Candidats aux examens', 'text' => 'Préparez le TCF, TEF, DELF/DALF ou les concours de la fonction publique avec un programme intensif et ciblé.'],
                    ['icon' => '🔝', 'title' => 'Apprenants souhaitant progresser rapidement', 'text' => 'Que ce soit pour améliorer votre oral, votre écrit ou une compétence spécifique, le 1-to-1 est la solution la plus efficace.'],
                ],
            ],
            [
                'slug' => 'ateliers',
                'name_fr' => 'Ateliers',
                'name_en' => 'Workshops',
                'description_fr' => 'Ateliers thématiques pour pratiquer et échanger en groupe',
                'description_en' => 'Thematic workshops to practice and exchange in a group',
                'image' => 'img/home/ateliers-new.png',
                'banner_image' => 'img/ateliers-banner.png',
                'order' => 7,
                'hero_subtitle' => 'Des ateliers thématiques pour pratiquer, échanger et perfectionner votre français dans une ambiance conviviale.',
                'hero_chips' => [
                    ['text' => 'Conversation', 'icon' => '<i class="fas fa-comments"></i>'],
                    ['text' => 'Culture', 'icon' => '🇨🇦', 'class' => 'm4-chip-green'],
                    ['text' => 'Maintien', 'icon' => '<i class="fas fa-book"></i>', 'class' => 'm4-chip-indigo'],
                    ['text' => '5 max', 'icon' => '<i class="fas fa-users"></i>', 'class' => 'm4-chip-amber'],
                ],
                'programs_intro' => 'Des formats variés pour tous les niveaux et tous les objectifs.',
                'description_html' => '<p>Nos ateliers sont des formats courts, conviviaux et efficaces pour pratiquer votre français régulièrement, dans une ambiance chaleureuse et sans pression.</p><p>Conversation, culture canadienne ou maintien du niveau : choisissez la thématique qui vous correspond et progressez à votre rythme, en petit groupe de 5 participants maximum.</p><p>Une heure par semaine suffit pour garder votre français vivant et développer votre aisance à l\'oral.</p>',
                'benefits_title' => 'Pourquoi choisir nos <span class="text-gradient">ateliers</span> ?',
                'benefits_intro' => 'Des formats courts, conviviaux et efficaces pour pratiquer votre français régulièrement.',
                'benefits' => [
                    ['icon' => '💬', 'title' => 'Pratique en situation réelle', 'text' => 'Des séances vivantes et interactives pour développer votre spontanéité et votre aisance à l\'oral.'],
                    ['icon' => '👥', 'title' => 'Petits groupes conviviaux', 'text' => 'Maximum 5 participants pour un espace bienveillant où chacun trouve sa place et ose parler.'],
                    ['icon' => '🎯', 'title' => 'Thématiques ciblées', 'text' => 'Conversation, culture canadienne ou maintien du niveau : choisissez l\'atelier qui vous correspond.'],
                    ['icon' => '💰', 'title' => 'Tarif accessible', 'text' => 'À partir de 100 $ pour 5 ateliers. Un investissement léger pour une progression régulière.'],
                ],
                'audience_intro' => 'Pour tous les adultes souhaitant pratiquer le français dans un cadre convivial et sans pression.',
                'audience' => [
                    ['icon' => '🌍', 'title' => 'Nouveaux arrivants au Canada', 'text' => 'Pratiquez votre français et découvrez la culture canadienne dans un espace bienveillant.'],
                    ['icon' => '💼', 'title' => 'Professionnels souhaitant s\'exprimer', 'text' => 'Améliorez votre aisance à l\'oral pour le travail ou les interactions quotidiennes.'],
                    ['icon' => '📚', 'title' => 'Apprenants en maintenance', 'text' => 'Entretenez votre niveau avec une pratique régulière et des séances légères.'],
                ],
            ],
        ];

        foreach ($categories as $data) {
            ServiceCategory::updateOrCreate(
                ['slug' => $data['slug']],
                $data
            );
        }
    }
}
