import json
import os

BASE = os.path.dirname(__file__)
with open(os.path.join(BASE, "service-colors.json")) as f:
    colors = json.load(f)

lines = [
    "/* Generated by extract-dominant-colors.py — do not edit manually */\n"
]

for sid, data in colors.items():
    c = data["primary"]
    r, g, b = int(c[1:3], 16), int(c[3:5], 16), int(c[5:7], 16)
    lines.append(f'/* {sid} */')
    lines.append(f'[data-service="{sid}"] {{ --accent: {c}; --accent-rgb: {r},{g},{b}; }}')
    lines.append(f'[data-service="{sid}"] .poc-badge {{ background: rgba({r},{g},{b},0.12); color: {c}; border-color: rgba({r},{g},{b},0.25); }}')
    lines.append(f'[data-service="{sid}"] .poc-price {{ color: {c}; }}')
    lines.append(f'[data-service="{sid}"] .poc-cta {{ color: {c}; }}')
    lines.append(f'[data-service="{sid}"] .poc-cta:hover {{ color: #fff; background: {c}; }}')
    lines.append(f'[data-service="{sid}"] .poc-image::after {{ background: linear-gradient(to top, rgba({r},{g},{b},0.4), transparent); }}')
    lines.append(f'[data-service="{sid}"] .poc-tags span {{ border-color: rgba({r},{g},{b},0.2); color: {c}; }}')
    lines.append(f'[data-service="{sid}"] .poc-footer {{ border-top-color: rgba({r},{g},{b},0.15); }}')
    lines.append(f'[data-service="{sid}"] .bubble {{ background: rgba({r},{g},{b},0.08); color: {c}; border-color: rgba({r},{g},{b},0.2); }}')
    lines.append(f'[data-service="{sid}"] .bubble:hover {{ background: {c}; color: #fff; border-color: {c}; }}')
    lines.append(f'[data-service="{sid}"] .ph-btn {{ background: {c}; border-color: {c}; }}')
    lines.append(f'[data-service="{sid}"] .ph-btn:hover {{ background: rgba({r},{g},{b},0.85); }}')
    lines.append(f'[data-service="{sid}"] .subservice-card-price {{ color: {c}; font-weight: 700; }}')
    lines.append(f'[data-service="{sid}"] .subservice-card-cta {{ color: {c}; }}')
    lines.append(f'[data-service="{sid}"] .subservice-card-cta:hover {{ color: #fff; background: {c}; }}')
    lines.append(f'[data-service="{sid}"] .badge {{ background: rgba({r},{g},{b},0.12); color: {c}; }}')
    lines.append(f'[data-service="{sid}"] .subservice-card-image::after {{ background: linear-gradient(to top, rgba({r},{g},{b},0.4), transparent); }}')
    lines.append(f'[data-service="{sid}"] .flagship-highlights .bubble {{ background: rgba({r},{g},{b},0.08); color: {c}; border-color: rgba({r},{g},{b},0.2); }}')
    lines.append(f'[data-service="{sid}"] .flagship-highlights .bubble:hover {{ background: {c}; color: #fff; border-color: {c}; }}')
    lines.append('')

out = os.path.join(BASE, "css", "service-themes.css")
with open(out, "w") as f:
    f.write("\n".join(lines))

print(f"Written {len(lines)} lines to {out}")
